/**
 * Menu Screen
 * Main menu with play, settings, and other options
 */

import React from 'react';
import { View, StyleSheet, ScrollView, Dimensions } from 'react-native';
import { ThemedText, ThemedButton, ThemedCard } from '../components/ThemedUI';
import { colors, spacing } from '../theme/generatedTheme';

const { height } = Dimensions.get('window');

export interface MenuScreenProps {
  gameName: string;
  onPlay: () => void;
  onSettings?: () => void;
  onAbout?: () => void;
}

export default function MenuScreen({
  gameName,
  onPlay,
  onSettings,
  onAbout
}: MenuScreenProps) {
  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Game title */}
        <View style={styles.titleContainer}>
          <ThemedText variant="title" bold align="center">
            {gameName}
          </ThemedText>
        </View>

        {/* Main menu card */}
        <ThemedCard variant="elevated" style={styles.menuCard}>
          <View style={styles.buttonContainer}>
            <ThemedButton
              title="Play"
              variant="primary"
              size="large"
              onPress={onPlay}
              style={styles.button}
            />

            {onSettings && (
              <ThemedButton
                title="Settings"
                variant="secondary"
                size="medium"
                onPress={onSettings}
                style={styles.button}
              />
            )}

            {onAbout && (
              <ThemedButton
                title="About"
                variant="secondary"
                size="medium"
                onPress={onAbout}
                style={styles.button}
              />
            )}
          </View>
        </ThemedCard>

        {/* Footer */}
        <View style={styles.footer}>
          <ThemedText variant="caption" color={colors.textSecondary} align="center">
            Generated by AI Game Generator
          </ThemedText>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing('huge'),
    minHeight: height * 0.9
  },
  titleContainer: {
    marginBottom: spacing('huge'),
    paddingHorizontal: spacing('large')
  },
  menuCard: {
    width: '85%',
    maxWidth: 400
  },
  buttonContainer: {
    gap: spacing('medium')
  },
  button: {
    width: '100%'
  },
  footer: {
    marginTop: spacing('huge'),
    paddingHorizontal: spacing('large')
  }
});
